production:
 adapter: postgresql
 encoding: unicode
 database: flydeas_production
 pool: 5
 username: root
 password:

development:
 adapter: postgresql
 encoding: unicode
 database: flydeas_development
 host: localhost
 port: 5432
 pool: 5
 username: postgres
 password:

test:
 adapter: postgresql
 encoding: unicode
 database: flydeas_test
 pool: 5
 username:
 password:
