development:
 adapter: postgresql
 encoding: unicode
 database: flydeas_development
 host: localhost
 port: 5432
 pool: 5
 username: bethhaubert
 password:

test:
 adapter: postgresql
 encoding: unicode
 database: flydeas_test
 pool: 5
 username:
 password:
